/** ASCII sprite for enemy `act6_wild_splinter` (Lasca Errante). */
export const sprite = [
  '     _                      _______                      _',
  '  _dMMMb._              .adOOOOOOOOOba.              _,dMMMb_',
  ' dP  ~YMMb            dOOOOOOOOOOOOOOOb            aMMP~  `Yb',
  ' V      ~"Mb          dOOOOOOOOOOOOOOOOOb          dM"~      V',
  '          `Mb.       dOOOOOOOOOOOOOOOOOOOb       ,dM',
  '           `YMb._   |OOOOOOOOOOOOOOOOOOOOO|   _,dMP',
  '      __     `YMMM| OP~"YOOOOOOOOOOOP"~`YO |MMMP     __',
  '    ,dMMMb.     ~~ OO     `YOOOOOP     OO `~~     ,dMMMb.',
  ' _,dP~  `YMba_      OOb      `OOO      dOO      _aMMP  ~Yb._',
  '<MMP     `~YMMa_   YOOo   @  OOO  @   oOOP   _adMP~      `YMM>',
  '             `YMMMM\`OOOo     OOO     oOOO/MMMMP',
  '     ,aa.     `~YMMb `OOOb._,dOOOb._,dOOOdMMP~       ,aa.',
  '   ,dMYYMba._         `OOOOOOOOOOOOOOOOO          _,adMYYMb.',
  '  ,MP   `YMMba._      OOOOOOOOOOOOOOOOO       _,adMMP   `YM.',
  '  MP        ~YMMMba._ YOOOOPVVVVVYOOOOP  _,adMMMMP~       `YM',
  '  YMb           ~YMMMM\`OOOOI`````IOOOOO/MMMMP~           dMP',
  '   `Mb.           `YMMMb`OOOI,,,,,IOOOOdMMMP           ,dM',
  '     `                  `OObNNNNNdOO                   `',
  '                           `~OOOOO~   TISSUE',
  '          ░ lasca ░,',
].join('\n');
